# RDS endpoint address generated by AWS after the instance is created
# Passed into EC2 module as db_host — app uses this to connect to the database
output "db_host" {
  description = "The RDS endpoint address"
  value       = aws_db_instance.rds_db.address
}

output "rds_sg_id" {
  description = "The RDS security group ID — used at root level for the EC2→RDS ingress rule"
  value       = aws_security_group.rds_sg.id
}

