# EC2 MODULE - VARIABLES

variable "project_name" {
  description = "The prefix for all resources"
  type = string
}

# Needed to attach the EC2 security group to the correct VPC
variable "vpc_id" {
  description = "The ID of the VPC"
  type = string
}

# EC2 is placed in private subnets — not directly reachable from internet
variable "private_subnet_ids" {
  description = "List of private subnet IDs for EC2 instances"
  type        = list(string)
}

# Used in EC2 ingress rule — only allows traffic from the ALB
variable "alb_security_group_id" {
  description = "The ID of alb security group for ec2 reference"
  type = string
}

# EC2 registers itself into this target group on creation
# This is what tells the ALB which EC2 instance to forward traffic to
variable "target_group_arn" {
  description = "The alb target group arn for ec2 to get registered "
}

# RDS endpoint address generated by AWS after RDS is created
variable "db_host" {
  description = "The RDS endpoint address"
  type = string
}

# Database credentials — same values passed to RDS module
variable "db_name" {
  description = "The name for the database"
  type = string
}

variable "db_username" {
  description = "the database username"
  type = string
}

variable "db_password" {
  description = "The database password"
  type = string
  sensitive = true
}
